title: RealLifeDiary # your site title
author: Jin Seongeun 
email: jseun112@naver.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  This is dotori's blog
baseurl: "/" # the subpath of your site, e.g. /blog
url: "reallifediary.com/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  jindotori # replace with your_github_username or comment to remove link from footer
instagram_username: reallife2da # replace with your_instagram_username or comment to remove link from footer
social:
  name: Your Name
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

disqus:
  shortname: reallifediary-com # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
remote_theme: sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

navigation:
 - {name: 'Home', link: '/'}
 - {name: 'About', link: '/about'}
 - {name: 'Posts', link: '/posts'}
   # - {name: 'Contacts', link: '/contacts'}

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
